Numpy

NumPy (Numerical Python) is a library used for numerical computing.
It gives you a super powerful object: the ndarray (N-dimensional array) — think of it like a list on steroids 💪.

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

# Create an array using numpy
arr1 = np.array([1, 2, 3, 4])
print(arr1)
print(type(arr1)) # <numpy.ndarray>
print(arr1.shape) # 1D array

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


In [ ]:
# Now lets reshape it to 2D array
arr2 = arr1.reshape(1, 4) # 1 row and 4 column
print(arr2)

[[1 2 3 4]]


In [ ]:
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr3) # 2D array
print(arr3.shape) # 2 row and 3 column

[[1 2 3]
 [4 5 6]]
(2, 3)


In [20]:
# Arrays built-in function
np.arange(0, 10, 2) # From 0 to 10 with skipping 1 element
# reshape it
np.arange(0, 10, 2).reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [22]:
# If I want to create array with all element to be 1
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
# Identity matrix
# I want all diagonal element become 1 and remaining 0
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
arr4 = np.array([2, 4, 6, 8])
print(arr4.shape)
print(arr4.ndim) # Array dimention
print(arr4.size) # Array size
print(arr4.dtype) # Array datatype

(4,)
1
4
int64


Numpy vectorized operation

In [28]:
arr5 = np.array([1, 2, 3, 4, 5])
arr6 = np.array([10, 10, 10, 10, 10])

print(arr5 + arr6)
print(arr5 * arr6)

[11 12 13 14 15]
[10 20 30 40 50]


In [ ]:
# Universal functions
arr7 = np.array([1, 3, 5, 7, 11])
print(np.sqrt(arr7)) # Square root
print(np.exp(arr7)) # Exponential
print(np.sin(arr7)) # Sine
print(np.log(arr7)) # Natural log

[1.         1.73205081 2.23606798 2.64575131 3.31662479]
[2.71828183e+00 2.00855369e+01 1.48413159e+02 1.09663316e+03
 5.98741417e+04]
[ 0.84147098  0.14112001 -0.95892427  0.6569866  -0.99999021]
[0.         1.09861229 1.60943791 1.94591015 2.39789527]


In [6]:
# Array slicing and indexing
mainArr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(mainArr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# Indexing
print(mainArr[1, 3])

8


In [ ]:
# Slicing
print(mainArr[2:]) # Complete 2nd row
print(mainArr[1:, 1:3])

[[ 9 10 11 12]]
[[ 6  7]
 [10 11]]


In [25]:
# Modify array element
mainArr[1, 2] = 100
mainArr[2:] = 99
print(mainArr)

[[  1   2   3   4]
 [  5   6 100   8]
 [ 99  99  99  99]]


Statistical Concepts - Normalization is to convert your data to have mean of 0 and standard deviation of 1

In [30]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print(mean)

# Median
median = np.median(data)
print(median)

# Standard deviation
std_dev = np.std(data)
print(std_dev)

# Variance
variance = np.var(data)
print(variance)

5.5
5.5
2.8722813232690143
8.25


In [33]:
# Logical operation
data > 5
data[data > 5] # array([ 6,  7,  8,  9, 10])

array([ 6,  7,  8,  9, 10])